/- GENERATED by research/cost_model_validation.py --emit-lean-certs.
   Each certificate instantiates the verified iteration bound with
   a design's binding cycle as found by the compiler's analysis.
   The bounds are relative to the analysis' declared latency table
   (see OP_LAT); the physical-delay refinement is documented in
   docs/cost-model-validation.md. -/
import IterationBound

namespace cert_rnn8
/-- rnn8: cycle mmh_a -> gs_a -> gb_a -> act (closing lag-1 delay edge). -/
def cycle : List Step := [⟨4, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 8 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_rnn8

namespace cert_rnn32
/-- rnn32: cycle mmh_a -> gs_a -> gb_a -> act (closing lag-1 delay edge). -/
def cycle : List Step := [⟨6, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 10 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_rnn32

namespace cert_gru8
/-- gru8: cycle mmh_r -> gs_r -> gb_r -> sig_r -> mul_nr -> tanh_n -> mul_a -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨4, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 13 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gru8

namespace cert_gru32
/-- gru32: cycle mmh_r -> gs_r -> gb_r -> sig_r -> mul_nr -> tanh_n -> mul_a -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨6, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 15 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gru32

namespace cert_lstm8
/-- lstm8: cycle mmh_f -> gs_f -> gb_f -> sig_f -> mul_fc -> c_upd -> tanh_c -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨4, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 13 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_lstm8

namespace cert_diag8
/-- diag8: cycle mul_ah -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_diag8

namespace cert_diag32
/-- diag32: cycle mul_ah -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_diag32

namespace cert_diag64
/-- diag64: cycle mul_ah -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_diag64

namespace cert_mgu16
/-- mgu16: cycle mmh_f -> gs_f -> gb_f -> sig_f -> mul_fh -> mmh_n -> gs_n -> gb_n -> tanh_n -> mul_b -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 21 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_mgu16

namespace cert_ugrnn16
/-- ugrnn16: cycle mmh_g -> gs_g -> gb_g -> sig_g -> one_minus -> mul_b -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 12 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_ugrnn16

namespace cert_indrnn16
/-- indrnn16: cycle mul_uh -> s_add -> b_add -> act (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 5 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_indrnn16

namespace cert_grurb16
/-- grurb16: cycle mmh_r -> gs_r -> gb_r -> sig_r -> mul_rh -> mmh_n -> gs_n -> gb_n -> tanh_n -> mul_a -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 21 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_grurb16

namespace cert_rnn16
/-- rnn16: cycle mmh_a -> gs_a -> gb_a -> act (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 9 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_rnn16

namespace cert_gru16
/-- gru16: cycle mmh_r -> gs_r -> gb_r -> sig_r -> mul_nr -> tanh_n -> mul_a -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 14 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gru16

namespace cert_lstm16
/-- lstm16: cycle mmh_f -> gs_f -> gb_f -> sig_f -> mul_fc -> c_upd -> tanh_c -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 14 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_lstm16

namespace cert_diag16
/-- diag16: cycle mul_ah -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_diag16

namespace cert_gruf8
/-- gruf8: cycle mmh_r -> gs_r -> gb_r -> sig_r -> mul_nr -> tanh_n -> mul_a -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 14 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gruf8

namespace cert_gruf16
/-- gruf16: cycle mmh_r -> gs_r -> gb_r -> sig_r -> mul_nr -> tanh_n -> mul_a -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 14 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gruf16

namespace cert_rnnf16
/-- rnnf16: cycle mmh_a -> gs_a -> gb_a -> act (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 9 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_rnnf16

namespace cert_rnn64
/-- rnn64: cycle mmh_a -> gs_a -> gb_a -> act (closing lag-1 delay edge). -/
def cycle : List Step := [⟨7, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 11 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_rnn64

namespace cert_janet16
/-- janet16: cycle mmh_f -> gs_f -> gb_f -> sig_f -> one_minus -> mul_b -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 12 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_janet16

namespace cert_sru16
/-- sru16: cycle vc_f -> s_f -> pb_f -> sig_f -> omf -> fb -> c_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 8 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_sru16

namespace cert_qrnn16
/-- qrnn16: cycle pa -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_qrnn16

namespace cert_mingru16
/-- mingru16: cycle pa -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_mingru16

namespace cert_fastgrnn16
/-- fastgrnn16: cycle mmh_s -> gs_s -> gb_s -> sig_z -> omz -> zscaled -> gain -> pa -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 14 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_fastgrnn16

namespace cert_ligru16
/-- ligru16: cycle mmh_z -> gs_z -> gb_z -> sig_z -> omz -> pb -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 12 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_ligru16

namespace cert_gru2l16
/-- gru2l16: cycle mmh_l1r -> gs_l1r -> gb_l1r -> sig_l1r -> mul_l1nr -> tanh_l1n -> pa_l1 -> upd_l1 (closing lag-1 delay edge). -/
def cycle : List Step := [⟨5, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨2, 0⟩, ⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 14 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gru2l16

namespace cert_gatedssm16
/-- gatedssm16: cycle sa -> h_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_gatedssm16

namespace cert_rwkv16
/-- rwkv16: cycle dnum -> num_upd (closing lag-1 delay edge). -/
def cycle : List Step := [⟨1, 0⟩, ⟨1, 0⟩, ⟨0, 1⟩]
example {II a : Int} (h : Chain II a cycle a) : 2 ≤ II := by
  have hb := iteration_bound h
  simp [cycle, totalLat, totalLag] at hb
  omega
end cert_rwkv16
